config/routes.rb
Picstory::Application.routes.draw do
  resources :commands

  resources :pictures
  post '/welcome/search' => 'welcome#search'
  post '/welcome/searchshow' => 'welcome#searchshow'
  get '/'  => 'welcome#index'
  get '/main' => 'welcome#main'
  get '/login' => 'welcome#login'
  get '/logout' => 'welcome#logout'
  post '/getphoto' => 'welcome#getphoto' 
  get '/getphoto_phone/:id'=>'welcome#getphoto_phone'
  post '/postdata' => 'welcome#postdata' 
  post '/command_post' => 'commands#command_post'
  get '/command_post' => 'commands#command_post'
  get '/command_page/:id' => 'commands#command_page'
  get '/welcome/photodetail/:id' => 'welcome#photodetail'
  post '/matchtag' => 'pictures#matchtag'
  post '/matchtag/:tag/:query' => 'pictures#matchtag'
  get '/matchtag' => 'pictures#matchtag'
  get '/matchtag/:tag/:query' => 'pictures#matchtag'
  get 'welcome/opencvfile'=>'welcome#opencvfile'
  match ':controller(/:action(/:id))(.:format)'
  root :to => 'welcome#index'

  

  
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :content, :image, :kind, :latitude, :longitude, :tag
  has_attached_file :image, :path => ":rails_root/app/assets/images/KaSza/:id.jpg", :url => "/assets/KaSza/:id.jpg", :default_url => "/assets/KaSza/:id.jpg"
  has_many :kaszas
  has_many :accounts, :through => :kaszas
end

app/controllers/pictures_controller.rb
# encoding: utf-8
require 'net/http'
class PicturesController < ApplicationController
  include RestGraph::RailsUtil
  before_filter :login_facebook, :only => [:login]
  before_filter :load_facebook, :except => [:login]
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end


  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])
    @picture.save
    rest_graph.access_token = cookies[:KaSzakey]
    @me = rest_graph.get('me')
    @a = Account.where(:fb_id => @me['id']).first
    @kasza = Kasza.new(:account_id => @a.id,:picture_id => @picture.id)
    @kasza.save
    # 算經緯度   如果算出來的差值小於10 就將他的id存下來 用陣列存取 陣列第一個數字是 要被比對的照片的id
    @closed = Array.new()
    @all = Picture.all
    la = @picture.latitude
    lo = @picture.longitude
    #@closed << params[:fbid]
    @all.each do |target|
      tla = (target.latitude).to_f - la.to_f
      tlo = (target.longitude).to_f - lo.to_f
      if ( (tla*tla + tlo*tlo) < 1 ) && (target.id != @picture.id)
         @closed << target.id.to_s
      end
    end
    #將經緯度差距的圖片用txt文字檔存起來，在目錄picstory之下 （並不是在picstory/app之下）
    aFile = File.new('test.txt','w')
    aFile.syswrite(@picture.id.to_s+"\n")
    aFile.syswrite(@closed)
    respond_to do |format|
      if @picture.save
        format.html { redirect_to '/main', notice: 'upload' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to '/main', notice: 'upload' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  # get /pictures/search/1
  # 尋找id=1 相同tag的照片
  def search
    @picture = Picture.find(params[:id])
    @tag = @picture
    @result = Picture.where(:tag=>@tag[:tag])
    @data = Array.new()
    @data << @result.count  
      

      @result.each do |picture|
        @temp = Hash.new {}
        @temp[:image] =  picture.image.url(:thumb)
        @temp[:content] = picture.content
        @temp[:id] = picture.id
        @data << @temp
      end
      render json: @data
  end

  #pictures/matchtag
  def matchtag
    #@target = Picture.find(params[:tag])
    #@query = Picture.find(params[:query])
    #@target.update_attributes(:tag=>@query.tag)
    data = Array.new()
    i = 0;
    f = File.open('./app/assets/images/KaSza/result.txt', "r") 
    f.each_line do |line|
      data[i] = line
      i = i+1
    end
    @target = Picture.find(data[0].to_i)
    @query = Picture.find(data[1].to_i)
    if @query.tag
      @target.update_attributes(:tag=>@query.tag)
    else
      @query.update_attributes(:tag=>@query.id.to_s)
      @target.update_attributes(:tag=>@query.tag)
    end
   
  end



################################################

    def login
    @me = rest_graph.get('/me')
    if Account.where(:fb_id => @me['id'])
    else
    @account = Account.new(:fb_id => @me['id'])
    @account.save
    end
    redirect_to '/main'
  end

  def logout
    reset_session
    cookies.delete(:KaSzakey)
    redirect_to '/'
  end
private
  def load_facebook
    rest_graph_setup(:write_session => true)
  end

  def login_facebook
    rest_graph_setup(:auto_authorize         => true,
                     :auto_authorize_scope   => 'publish_checkins',
                     :ensure_authorized      => true,
                     :write_session          => true)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/_form2.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image ,:onchange =>"yulan(this)"%>
    <div id="preview"></div>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/_form3.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>
<div>
<%= render 'form' %>
</div>
<div id='editload'>
<%= render 'form3' %>
</div>
<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Kind</th>
    <th>Content</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= image_tag picture.image.url(:thumb) %></td>
    <td><%= picture.kind %></td>
    <td><%= picture.content %></td>
    <td><%= picture.latitude %></td>
    <td><%= picture.longitude %></td>
    <td><%= picture.tag %></td>
    <td><%= link_to 'Show', picture %></td>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
    <td><%= link_to 'Destroy', picture, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>
<div id='pic_upload'>
<%= render 'form2' %>
</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= image_tag @picture.image.url(:thumb) %>
</p>

<p>
  <b>Kind:</b>
  <%= @picture.kind %>
</p>

<p>
  <b>Content:</b>
  <%= @picture.content %>
</p>

<p>
  <b>Latitude:</b>
  <%= @picture.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @picture.longitude %>
</p>

<p>
  <b>Tag:</b>
  <%= @picture.tag %>
</p>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>