config/routes.rb
Picstory::Application.routes.draw do
  resources :commands

  resources :pictures
  post '/welcome/search' => 'welcome#search'
  post '/welcome/searchshow' => 'welcome#searchshow'
  get '/'  => 'welcome#index'
  get '/main' => 'welcome#main'
  get '/login' => 'welcome#login'
  get '/logout' => 'welcome#logout'
  post '/getphoto' => 'welcome#getphoto' 
  get '/getphoto_phone/:id'=>'welcome#getphoto_phone'
  post '/postdata' => 'welcome#postdata' 
  post '/command_post' => 'commands#command_post'
  get '/command_post' => 'commands#command_post'
  get '/command_page/:id' => 'commands#command_page'
  get '/welcome/photodetail/:id' => 'welcome#photodetail'
  post '/matchtag' => 'pictures#matchtag'
  post '/matchtag/:tag/:query' => 'pictures#matchtag'
  get '/matchtag' => 'pictures#matchtag'
  get '/matchtag/:tag/:query' => 'pictures#matchtag'
  get 'welcome/opencvfile'=>'welcome#opencvfile'
  match ':controller(/:action(/:id))(.:format)'
  root :to => 'welcome#index'

  

  
end

app/models/command.rb
class Command < ActiveRecord::Base
  attr_accessible :content, :fb_id, :fb_name, :picture_id
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @commands }
    end
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
    @command = Command.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @command }
    end
  end

  # GET /commands/new
  # GET /commands/new.json
  def new
    @command = Command.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @command }
    end
  end

  # GET /commands/1/edit
  def edit
    @command = Command.find(params[:id])
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(params[:command])

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render json: @command, status: :created, location: @command }
      else
        format.html { render action: "new" }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /commands/1
  # PUT /commands/1.json
  def update
    @command = Command.find(params[:id])

    respond_to do |format|
      if @command.update_attributes(params[:command])
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command = Command.find(params[:id])
    @command.destroy

    respond_to do |format|
      format.html { redirect_to commands_url }
      format.json { head :no_content }
    end
  end

  def command_post
    @command = Command.new(:picture_id=>params[:picture_id],:fb_id=>params[:fb_id],:fb_name=>params[:fb_name],:content=>params[:content]);
    @command.save
    #render "created success"
    
  end

  def command_page
    @commands = Command.where(:picture_id=>params[:id])

  end

end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.erb
<%= form_for(@command) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% @command.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :picture_id %><br />
    <%= f.text_field :picture_id %>
  </div>
  <div class="field">
    <%= f.label :fb_id %><br />
    <%= f.text_field :fb_id %>
  </div>
  <div class="field">
    <%= f.label :fb_name %><br />
    <%= f.text_field :fb_name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commands/command_page.html.erb
<div id='command_page'>
<% @commands.each do |command| %>
<div class='command_list'>
<p class='command_content'><span class='command_name'><%= command.fb_name %>&nbsp;：&nbsp;</span><%= command.content %></p>

</div>
<%end%>

</div>

app/views/commands/edit.html.erb
<h1>Editing command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<h1>Listing commands</h1>

<table>
  <tr>
    <th>Picture</th>
    <th>Fb</th>
    <th>Fb name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commands.each do |command| %>
  <tr>
    <td><%= command.picture_id %></td>
    <td><%= command.fb_id %></td>
    <td><%= command.fb_name %></td>
    <td><%= command.content %></td>
    <td><%= link_to 'Show', command %></td>
    <td><%= link_to 'Edit', edit_command_path(command) %></td>
    <td><%= link_to 'Destroy', command, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Command', new_command_path %>

app/views/commands/new.html.erb
<h1>New command</h1>

<%= render 'form' %>

<%= link_to 'Back', commands_path %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Picture:</b>
  <%= @command.picture_id %>
</p>

<p>
  <b>Fb:</b>
  <%= @command.fb_id %>
</p>

<p>
  <b>Fb name:</b>
  <%= @command.fb_name %>
</p>

<p>
  <b>Content:</b>
  <%= @command.content %>
</p>


<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>